# Generated by Django 2.2.4 on 2019-10-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('jobtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('studentName', models.TextField()),
                ('studentSurname', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(max_length=100)),
                ('buildingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Building')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Module')),
                ('venueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Module')),
                ('studentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Module')),
                ('venueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Venue')),
            ],
            options={
                'unique_together': {('venueID', 'period'), ('venueID', 'day')},
            },
        ),
    ]
