# Generated by Django 2.2.4 on 2019-10-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='path',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
