# Generated by Django 2.2.4 on 2019-10-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_venue_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolement',
            old_name='studentNumber',
            new_name='student',
        ),
    ]
