# Generated by Django 2.2.4 on 2019-10-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20191002_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.IntegerField(),
        ),
    ]
