# Generated by Django 2.2.4 on 2019-10-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20191002_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('venueID', 'period', 'day')},
        ),
    ]
