# Generated by Django 2.2.4 on 2019-10-03 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_auto_20191002_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='enrolement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examtimetable',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
