# Generated by Django 2.2.4 on 2019-10-06 14:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0007_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolement',
            old_name='moduleID',
            new_name='module',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='path',
        ),
        migrations.AddField(
            model_name='building',
            name='buildingPlan',
            field=models.ImageField(default='/api_app/bob.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='date',
            field=models.DateField(default=datetime.date(2019, 10, 6)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='examtimetable',
            unique_together={('venueID', 'period', 'date')},
        ),
        migrations.CreateModel(
            name='BookedVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Venue')),
            ],
        ),
        migrations.RemoveField(
            model_name='examtimetable',
            name='day',
        ),
    ]
