# Generated by Django 2.2.4 on 2019-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_auto_20191006_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='buildingPlan',
            field=models.ImageField(upload_to=''),
        ),
    ]
