# Generated by Django 2.2.4 on 2019-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_auto_20191006_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='x',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='y',
            field=models.CharField(default='z', max_length=255),
            preserve_default=False,
        ),
    ]
