# Generated by Django 2.2.4 on 2019-10-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_auto_20191019_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolement',
            name='year',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
