# Generated by Django 2.2.4 on 2019-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_enrolement_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='venue',
            name='venuePath',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
